version: "3.8"

services:
  devops-lab:
    build: .
    container_name: devops-lab
    privileged: true
    ports:
      - "6443:6443"   # API de Kubernetes
      - "3000:3000"   # Grafana
      - "9090:9090"   # Prometheus
    volumes:
      - k3s_data:/var/lib/rancher/k3s
      - kubeconfig:/output
      - ./terraform:/workspace/terraform
    working_dir: /workspace/terraform
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=644
      - KUBECONFIG=/output/kubeconfig.yaml

volumes:
  k3s_data:
  kubeconfig:
