name: 99 Terraform Destroy
on:
  workflow_run:
    workflows: [ "99 Destroy project" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  tf-destroy:
    if: ${{ github.event_name == 'workflow_dispatch' || ( github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' ) }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v1

      - name: Create Public Access Key
        run: echo "${{ secrets.PUBLIC_ACCESS_KEY }}" > remote-host-control.pub

      - name: Install Terraform
        env:
          TERRAFORM_VERSION: "1.10.5"
        run: |
          wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
          unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Terraform init
        run: terraform init -input=false -no-color

      - name: Terraform destroy
        run: terraform destroy -auto-approve -no-color