name: Deploy to EKS from EC2

on:
  workflow_dispatch:  # lo podés lanzar manualmente desde la pestaña Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy deployment files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./scripts/deploy.sh,./k8s"
        target: "~/"

    - name: Run deployment script on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          chmod +x ~/scripts/deploy.sh
          ~/scripts/deploy.sh
